### ISSUE TITLE
Ignores CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by GyrosGeier** [tpaviot/oce#634]
The standard way to specify an install prefix in CMake is to set the CMAKE_INSTALL_PREFIX variable.

The master CMakeLists.txt however overwrites this, so the default setting is ignored, and the install target installs into C:\OCE-0.18-dev.

Is it possible to reverse this logic to avoid interesting surprises?

**Comment by thatcadguy** [comment]
I think they set things up the way they did because no one wants include, bin, etc directories in C:\Program Files on Windows. On non-Windows platforms, it keeps the default of /usr/local. You can look at CMakeLists.txt lines 234-248 though and propose how you think it should work. I think the only possible change would be to see if CMAKE_INSTALL_PREFIX is not the default setting, and if OCE_INSTALL_PREFIX is not set, then use whatever CMAKE_INSTALL_PREFIX is set to.
